import { Router, type IRouter } from "express";
import healthRouter from "./health";
import categoriesRouter from "./categories";
import projectsRouter from "./projects";
import imagesRouter from "./images";
import servicesRouter from "./services";
import adminRouter from "./admin";
import settingsRouter from "./settings";
import pageContentRouter from "./page_content";
import aiRouter from "./ai";
import documentsRouter from "./documents";
import galleryRouter from "./gallery";
import clientsRouter from "./clients";
import policiesRouter from "./policies";
import messagesRouter from "./messages";
import blogRouter from "./blog";
import mediaRouter from "./media";
import testimonialsRouter from "./testimonials";
import jobsRouter from "./jobs";

const router: IRouter = Router();

router.use(healthRouter);
router.use(categoriesRouter);
router.use(projectsRouter);
router.use(imagesRouter);
router.use(servicesRouter);
router.use(adminRouter);
router.use(settingsRouter);
router.use(pageContentRouter);
router.use(aiRouter);
router.use(documentsRouter);
router.use(galleryRouter);
router.use(clientsRouter);
router.use(policiesRouter);
router.use(messagesRouter);
router.use(blogRouter);
router.use(mediaRouter);
router.use(testimonialsRouter);
router.use(jobsRouter);

export default router;
