import type { Project, ProjectSummary, ServicesItem } from "@workspace/api-client-react";

const IMG = (id: string, w = 900) => `https://images.unsplash.com/${id}?w=${w}&q=75`;

export const FALLBACK_PROJECTS: ProjectSummary[] = [
  { id: 1, title: "Obsidian Cultural Centre", slug: "obsidian-cultural-centre", location: "Dubai, UAE", client: "Dubai Municipality", sector: "Cultural", status: "Completed", published: true, featured: true, categoryId: 4, year: "2023", categoryName: "Cultural", heroImage: IMG("photo-1470723710355-95304d8aece4") },
  { id: 2, title: "Meridian Tower", slug: "meridian-tower", location: "Shenzhen, China", client: "Meridian Group", sector: "Commercial", status: "Completed", published: true, featured: true, categoryId: 1, year: "2022", categoryName: "Commercial", heroImage: IMG("photo-1486325212027-8081e485255e") },
  { id: 3, title: "Heliodor Residences", slug: "heliodor-residences", location: "Monaco", client: "Heliodor Properties", sector: "Residential", status: "Completed", published: true, featured: true, categoryId: 2, year: "2023", categoryName: "Residential", heroImage: IMG("photo-1512917774080-9991f1c4c750") },
  { id: 4, title: "Civic Axis Masterplan", slug: "civic-axis-masterplan", location: "Riyadh", client: "Royal Commission for Riyadh City", sector: "Infrastructure", status: "In Progress", published: true, featured: true, categoryId: 5, year: "2024", categoryName: "Infrastructure", heroImage: IMG("photo-1477959858617-67f85cf4f1df") },
  { id: 5, title: "Quay District Towers", slug: "quay-district-towers", location: "Auckland", client: "Quay Development Ltd", sector: "Commercial", status: "Completed", published: true, featured: true, categoryId: 1, year: "2021", categoryName: "Commercial", heroImage: IMG("photo-1515263487990-61b07816b324") },
  { id: 6, title: "Solaris Industrial Complex", slug: "solaris-industrial-complex", location: "Jeddah", client: "Solaris Industries", sector: "Industrial", status: "Completed", published: true, featured: false, categoryId: 3, year: "2022", categoryName: "Industrial", heroImage: IMG("photo-1503387762-592deb58ef4e") },
  { id: 7, title: "Azure Heights", slug: "azure-heights", location: "Dubai Marina", client: "Azure Properties", sector: "Residential", status: "In Progress", published: true, featured: false, categoryId: 2, year: "2024", categoryName: "Residential", heroImage: IMG("photo-1545324418-cc1a3fa10c00") },
  { id: 8, title: "Verdant Civic Park", slug: "verdant-civic-park", location: "Islamabad", client: "Capital Development Authority", sector: "Public", status: "Completed", published: true, featured: false, categoryId: 5, year: "2020", categoryName: "Infrastructure", heroImage: IMG("photo-1448630360428-65456885c650") },
  { id: 9, title: "Atrium Business Hub", slug: "atrium-business-hub", location: "Karachi", client: "Atrium Holdings", sector: "Commercial", status: "Completed", published: true, featured: false, categoryId: 1, year: "2019", categoryName: "Commercial", heroImage: IMG("photo-1497366216548-37526070297c") },
];

export function buildFallbackProject(slug: string): Project | null {
  const summary = FALLBACK_PROJECTS.find(p => p.slug === slug);
  if (!summary) return null;
  return {
    ...summary,
    size: undefined,
    scope: undefined,
    longDescription: `${summary.title} is a landmark ${(summary.sector || "architectural").toLowerCase()} project delivered for ${summary.client || "our client"} in ${summary.location || "the region"}. The project reflects our commitment to design excellence, technical rigour, and buildability — combining contextual sensitivity with the structural demands of a modern ${summary.sector || "built"} environment.\n\nDelivered under a design-build framework, the scheme integrates sustainable materials, efficient MEP systems, and a clear parti that responds to climate, culture, and end-user needs. The result is a high-performing asset that elevates the surrounding public realm and stands the test of time.`,
    images: [
      { id: 1, projectId: summary.id, imageUrl: summary.heroImage || IMG("photo-1486325212027-8081e485255e"), isHero: true, sortOrder: 0 },
      { id: 2, projectId: summary.id, imageUrl: IMG("photo-1497366216548-37526070297c"), isHero: false, sortOrder: 1 },
      { id: 3, projectId: summary.id, imageUrl: IMG("photo-1497366811353-6870744d04b2"), isHero: false, sortOrder: 2 },
      { id: 4, projectId: summary.id, imageUrl: IMG("photo-1503387762-592deb58ef4e"), isHero: false, sortOrder: 3 },
    ] as any,
  } as Project;
}

const SRV_IMG = (id: string) => IMG(id, 600);

export const FALLBACK_SERVICES: ServicesItem[] = [
  { id: 1, name: "General Contracting", slug: "general-contracting", description: "Turnkey delivery of commercial, residential, and industrial buildings — one accountable team from mobilisation to handover.", longDescription: "As a general contractor, Azhar Engineering (Pvt.) Ltd takes full responsibility for delivering your project on time and on budget. We coordinate every trade, manage the supply chain, and hold a single point of accountability across the entire programme.\n\nFrom foundations to finishes, our experienced site teams, quality engineers, and safety officers work to the same disciplined standards on every site. Clients benefit from transparent reporting, proactive risk management, and a build quality that protects the value of the asset for decades.", imageUrl: SRV_IMG("photo-1504307651254-35680f356dfd"), published: true, featured: true, projectCount: 12, projects: [1, 6, 8, 9].map(id => FALLBACK_PROJECTS.find(p => p.id === id)).filter((p): p is ProjectSummary => Boolean(p)) },
  { id: 2, name: "Design & Build", slug: "design-and-build", description: "Architecture and engineering integrated with construction to compress schedules and eliminate coordination gaps.", longDescription: "Our design-build service unites architects, structural engineers, and construction teams under one contract. This integrated approach removes the friction between design and site, compresses programme durations, and protects the client from cost overruns.\n\nWe manage the full lifecycle — concept, detailed design, approvals, construction, and commissioning — so every decision is made with buildability and budget in mind.", imageUrl: SRV_IMG("photo-1486718448742-163732cd1544"), published: true, featured: true, projectCount: 8, projects: [3, 5, 7].map(id => FALLBACK_PROJECTS.find(p => p.id === id)).filter((p): p is ProjectSummary => Boolean(p)) },
  { id: 3, name: "Civil Construction", slug: "civil-construction", description: "Infrastructure and heavy civil works including earthworks, foundations, concrete structures, and site development.", longDescription: "From bulk earthworks to complex reinforced-concrete structures, our civil construction capability is backed by one of the most modern equipment fleets in the region.\n\nWe self-perform excavation, piling, formwork, rebar, and concrete placement to keep quality and schedule firmly in our own hands. Whether it is a deep basement, a bridge substructure, or a full site development, our teams deliver to exacting engineering standards.", imageUrl: SRV_IMG("photo-1477959858617-67f85cf4f1df"), published: true, featured: true, projectCount: 9, projects: [4, 6].map(id => FALLBACK_PROJECTS.find(p => p.id === id)).filter((p): p is ProjectSummary => Boolean(p)) },
  { id: 4, name: "MEP & Electrical Works", slug: "mep-and-electrical-works", description: "Mechanical, electrical, and plumbing systems engineered for efficiency, safety, and long-term operability.", longDescription: "Building services are where a structure becomes a functional, comfortable, and efficient building. Our MEP division designs, installs, and commissions HVAC, electrical, plumbing, fire-fighting, and low-voltage systems.\n\nCoordinated through detailed 3D models before site works begin, our MEP delivery minimises clashes, reduces rework, and ensures every system is tested and documented before handover.", imageUrl: SRV_IMG("photo-1581092160607-ee22621dd758"), published: true, featured: true, projectCount: 6, projects: [5].map(id => FALLBACK_PROJECTS.find(p => p.id === id)).filter((p): p is ProjectSummary => Boolean(p)) },
  { id: 5, name: "Project Management", slug: "project-management", description: "Owner's representation, programme control, cost management, and quality assurance across the project lifecycle.", longDescription: "We act as the owner's representative to keep complex projects on track. Our project managers control the programme, monitor costs against budget, and enforce quality standards across every consultant and contractor.\n\nWith robust reporting cadences and early-warning systems, we give clients total visibility and the confidence that decisions are made with accurate, current information.", imageUrl: SRV_IMG("photo-1454165804606-c3d57bc86b40"), published: true, featured: true, projectCount: 7, projects: [2, 7].map(id => FALLBACK_PROJECTS.find(p => p.id === id)).filter((p): p is ProjectSummary => Boolean(p)) },
  { id: 6, name: "Structural Engineering", slug: "structural-engineering", description: "Structural design, analysis, and peer review for high-rises, industrial facilities, and special structures.", longDescription: "Our structural engineering team designs safe, efficient, and constructible structures for some of the most demanding building types in the region.\n\nFrom tall buildings in high-wind zones to industrial facilities carrying heavy plant loads, we deliver optimised designs that reduce material cost while meeting every code requirement — and we stand behind them through construction with full site supervision.", imageUrl: SRV_IMG("photo-1431576901776-e539bd916ba2"), published: true, featured: false, projectCount: 5, projects: [2, 4].map(id => FALLBACK_PROJECTS.find(p => p.id === id)).filter((p): p is ProjectSummary => Boolean(p)) },
  { id: 7, name: "Renovation & Fit-out", slug: "renovation-and-fitout", description: "Refurbishment and interior fit-out for offices, retail, and hospitality — with minimal disruption to operations.", longDescription: "We transform existing spaces with specialist refurbishment and fit-out delivery. Working after hours where required, our teams manage demolition, structural alterations, and premium finishes to tight programmes.\n\nFrom boardroom interiors to complete office floorplates, we deliver high-end fit-outs that are safe, discreet, and on schedule — so your business keeps operating throughout.", imageUrl: SRV_IMG("photo-1497366811353-6870744d04b2"), published: true, featured: false, projectCount: 4, projects: [3, 9].map(id => FALLBACK_PROJECTS.find(p => p.id === id)).filter((p): p is ProjectSummary => Boolean(p)) },
];

export function buildFallbackService(slug: string): ServicesItem | null {
  return FALLBACK_SERVICES.find(s => s.slug === slug) ?? null;
}
